set nocompatible
set mouse=a
set ruler
set showmode
set showcmd
set hlsearch
set incsearch
set ignorecase
set smartcase
set number
set showmatch
set matchtime=1
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
syntax on
set background=dark
colorscheme Tomorrow-Night-Eighties
